include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - 'vendor/**'
    - 'test/**'
    - 'packages/**'
linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    one_member_abstracts: false
    # Will be disabled and required once other linting rules have been fixed
    prefer_relative_imports: false
    public_member_api_docs: false
    curly_braces_in_flow_control_structures: false
    unnecessary_this: false
    avoid_catches_without_on_clauses: false
