include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - 'test/**'

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    avoid_types_on_closure_parameters: false
    constant_identifier_names: false
    omit_local_variable_types: false
    public_member_api_docs: false
    always_use_package_imports: true
    # Will be disabled and required once other linting rules have been fixed
    curly_braces_in_flow_control_structures: false
    unnecessary_this: false
    avoid_catches_without_on_clauses: false
