#!/usr/bin/env bash

flutter clean
flutter build ios
cd ios
xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath ./build/Runner.xcarchive
xcodebuild -exportArchive -archivePath ./build/Runner.xcarchive -exportOptionsPlist ./ExportOptions.plist -exportPath ./build/Runner.ipa
cd ..
cp ios/build/Runner.ipa/Runner.ipa ./LunaSea.ipa
rm -rf build ios/build
