default_platform(:mac)
build_number = 1000000000 + number_of_commits()

platform :mac do
  desc "Deploy a new alpha build to TestFlight"
  lane :alpha do
    if is_ci
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end

    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APPLE_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APPLE_STORE_CONNECT_KEY_FILEPATH"],
    )

    sh("flutter", "build", "macos", "--release", "--build-number=#{build_number}")
    build_mac_app(scheme: "Runner", workspace: "Runner.xcworkspace", export_method: "app-store")

    upload_to_testflight(
      distribute_external: false,
      notify_external_testers: false,
      reject_build_waiting_for_review: true,
      groups: "Alpha",
      changelog: "The changelog is available within the application!",
    )
  end
end
