name: radarr
description: radarr
version: 0.0.1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1
dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.16.8
scripts:
  build: pub run build_runner build --delete-conflicting-outputs
