name: wake_on_lan
description: Send wake on LAN magic packets to devices on your local network.
version: 2.0.1+3
homepage: https://github.com/CometTools/LunaSea/tree/master/packages/wake_on_lan
repository: https://github.com/CometTools/LunaSea/tree/master/packages
issue_tracker: https://github.com/CometTools/LunaSea/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  convert: ^3.0.0
dev_dependencies:
  test: ^1.18.2
scripts:
  coverage: test_coverage --no-badge
  netcat: nc -ul 9 | hexdump -C
