default_platform(:ios)

platform :ios do
  desc "Deploy a new build to Testflight"
  lane :beta do
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios", "--release", "--bundle-sksl-path=shaders/ios_sksl.json", "--no-codesign")
    end
    build_ios_app(scheme: "Runner")
    # upload_to_testflight
  end
end
