default_platform(:ios)
build_number = 1000000000 + number_of_commits()

platform :ios do
  desc "Deploy a new alpha build to TestFlight"
  lane :alpha do
    Dir.chdir "../.." do
      sh("flutter", "clean")
      sh("flutter", "packages", "get")
      sh("flutter", "build", "ios", "--release", "--bundle-sksl-path=shaders/ios_sksl.json", "--no-codesign", "--build-number=#{build_number}")
    end
    api_key = app_store_connect_api_key(
      key_id: "3Z55GTHMWY",
      issuer_id: "057b0968-cbc8-4025-99da-84fb326bed70",
      key_filepath: "./Auth.p8",
    )
    build_ios_app(scheme: "Runner", workspace: "Runner.xcworkspace", export_method: "app-store")
    upload_to_testflight(distribute_external: true, groups: "Alpha")
  end
end
