/// Flutter icons LunaBrandIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LunaBrandIcons
///      fonts:
///       - asset: fonts/LunaBrandIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LunaBrandIcons {
  LunaBrandIcons._();

  static const _kFontFam = 'LunaBrandIcons';
  static const String? _kFontPkg = null;

  static const IconData bravebrowser = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lidarr = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoftedge = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nzbget = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData overseerr = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plex = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radarr = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sabnzbd = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safari = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sonarr = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tautulli = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData readarr = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
