name: overseerr
description: overseerr
version: 0.0.1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1
dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  test: ^1.16.5
scripts:
  build: pub run build_runner build --delete-conflicting-outputs
