export './routes/settings.dart';
export './routes/general.dart';
export './routes/system.dart';
export './routes/modules.dart';
// Modules
export './routes/modules/automation_lidarr.dart';
export './routes/modules/automation_radarr.dart';
export './routes/modules/automation_sonarr.dart';
export './routes/modules/clients_nzbget.dart';
export './routes/modules/clients_sabnzbd.dart';
export 'routes/modules/general_home.dart';
export './routes/modules/general_lunasea.dart';
export './routes/modules/general_search.dart';
export './routes/modules/general_search_add.dart';
export './routes/modules/general_search_edit.dart';
export './routes/modules/general_wake_on_lan.dart';
// Logs
export './routes/logs/logs_details.dart';
export './routes/logs/logs_types.dart';
export './routes/logs/logs_view.dart';
// System
export './routes/system/resources_donations.dart';
export './routes/system/resources_donations_thankyou.dart';
