#!/usr/bin/env bash

cd ..
# Remove old builds
rm -rf ./LunaSea.ipa
# Clean and build
flutter clean
flutter build ios
# Export build to IPA
cd ios
xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath ./build/Runner.xcarchive
xcodebuild -exportArchive -archivePath ./build/Runner.xcarchive -exportOptionsPlist ./ExportOptions.plist -exportPath ./build/Runner.ipa
# Copy IPA to root of project
cd ..
cp ios/build/Runner.ipa/Runner.ipa ./LunaSea.ipa
# Remove build files
rm -rf build
rm -rf build ios/build
