#!/usr/bin/env bash

cd ..
# Remove old builds
rm -rf ./LunaSea-arm64-v8a-release.apk
rm -rf ./LunaSea-armeabi-v7a-release.apk
rm -rf ./LunaSea-x86_64-release.apk
# Clean and build
flutter clean
flutter build apk --split-per-abi
# Copy APKs to root of project
cp ./build/app/outputs/apk/release/app-armeabi-v7a-release.apk ./LunaSea-armeabi-v7a-release.apk
cp ./build/app/outputs/apk/release/app-arm64-v8a-release.apk ./LunaSea-arm64-v8a-release.apk
cp ./build/app/outputs/apk/release/app-x86_64-release.apk ./LunaSea-x86_64-release.apk
# Remove build files
rm -rf ./build
