name: tautulli
description: Facilitate the communication to and from Tautulli's API, a Python based monitoring and tracking tool for Plex Media Server.
version: 2.0.0+1
homepage: https://github.com/CometTools/LunaSea/tree/master/packages/tautulli
repository: https://github.com/CometTools/LunaSea/tree/master/packages
issue_tracker: https://github.com/CometTools/LunaSea/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1
dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.16.8
scripts:
  build: pub run build_runner build --delete-conflicting-outputs
