default_platform(:android)

platform :android do
  desc "Build App Bundle"
  lane :build do |options|
    sh("flutter", "build", "appbundle", "--release", "--bundle-sksl-path=shaders/android_sksl.json", "--build-number=#{options[:build_number]}")
  end

  desc "Deploy to Google Play Store"
  lane :deploy do |options|
    upload_to_play_store(
      aab: options[:aab] || "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: options[:track] || "internal",
      version_name: options[:version_name] || "Unknown Version",
    )
  end

  desc "Deploy metadata changes to Google Play"
  lane :metadata do
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
    )
  end
end
