name: sonarr
description: Facilitate the communication to and from Sonarr's API, a smart PVR for newsgroup and bittorrent users.
version: 3.0.0
homepage: https://github.com/CometTools/LunaSea/tree/master/packages/sonarr
repository: https://github.com/CometTools/LunaSea/tree/master/packages
issue_tracker: https://github.com/CometTools/LunaSea/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  meta: ^1.3.0
dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^5.0.2
  test: ^1.18.2
scripts:
  build: dart run build_runner build --delete-conflicting-outputs
