name: iOS Alpha Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0

      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v2.0.3
        with:
          flutter-version: '2.9.0-0.1.pre'
          channel: 'beta'

      - name: Install Pods
        working-directory: ${{ github.workspace }}/ios
        run: |
          pod install --repo-update
      
      - name: Setup Keystore & Firebase
        working-directory: ${{ github.workspace }}
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }} | base64 --decode > ios/GoogleService-Info.plist
          echo ${{ secrets.P8_3Z55GTHMWY }} | base64 --decode > ios/fastlane/3Z55GTHMWY.p8

      - name: Run Fastlane
        working-directory: ${{ github.workspace }}/ios
        run: |
          bundle install
          bundle exec fastlane alpha
