name: '[GitHub] Issues - Feature Requests'

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-20.04
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: 'feature request'
          issue-comment: >
            Hi @{issue-author}! We use the issue tracker exclusively
            for bug reports and issues. However, this issue appears
            to be a feature request. Please use the following channels:

            - [Feedback & Feature Requests Board](https://feedback.lunasea.app)

            - [Discord](https://www.lunasea.app/discord)
          close-issue: true
          lock-issue: true
          issue-lock-reason: 'off-topic'
