name: '[Discord] Update Discord Build Status'

on:
  workflow_call:
    inputs:
      STATUS:
        required: true
        type: string
      FLAVOR:
        required: true
        type: string

    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  run:  
    name: Update Discord Channel
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message
        with:
          description: "Build and deploy `${{ inputs.FLAVOR }}` build"
          status: ${{ inputs.STATUS }}
          title: '[Release] ${{ inputs.FLAVOR }}'
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
